name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # или master, в зависимости от названия основной ветки

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.0'

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Build site
        working-directory: scicarve-site
        run: hugo
      
      - name: Add CNAME file
        run: echo 'www.carvebook.ru' > ./scicarve-site/public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scicarve-site/public
          publish_branch: gh-pages
